Added Pebble support
micronaut-projects/micronaut-views pull request #129
Opened 2020-11-25 15:27 UTC by ecmel

Fixes issue https://github.com/micronaut-projects/micronaut-views/issues/127

2020-11-25 15:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-views?pullRequest=129) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-views?pullRequest=129) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-views?pullRequest=129) it.</sub>

2020-11-25 16:15 UTC, graemerocher commented
Nice, don't worry about the failure, it is related to our test report publishing

2020-11-25 16:34 UTC, alvarosanchez requested changes

2020-11-25 16:34 UTC, alvarosanchez commented on views-pebble/src/main/resources/META-INF/native-image/io.micronaut.views.handlebars/native-image.properties
> +Args = --initialize-at-build-time=com.mitchellbosecke.pebble
File should be renamed

2020-11-25 16:45 UTC, ecmel commented on views-pebble/src/main/resources/META-INF/native-image/io.micronaut.views.handlebars/native-image.properties
> +Args = --initialize-at-build-time=com.mitchellbosecke.pebble
Fixed

2020-11-25 16:56 UTC, ilopmar requested changes
As this is a new feature it should go in a next minor version. Please change the `@since` tags to 2.2.0.

2020-11-25 16:58 UTC, ilopmar commented
@ecmel One question. Did you try GraalVM to test that it actually works? In that case it would be great to add a new test application to our official test-suite. Please take a look at the examples here: https://github.com/micronaut-graal-tests/micronaut-views-graal
It's a matter of creating a new branch, in this case it would be `2.3.x_pebble` based on any 2.2.x_... branch that already exist.

2020-11-26 06:41 UTC, ecmel commented
@ilopmar I will add the test for graalvm.

On the other hand, Pebble has a parallel rendering [feature](https://pebbletemplates.io/wiki/guide/high-performance/) with an `ExecuterService`. Is it okey to add TaskExecuters.IO to the Builder? I am not sure if this feature is used a lot.

2020-11-26 15:21 UTC, alvarosanchez approved these changes

2020-11-26 16:09 UTC, ilopmar approved these changes

2020-11-26 22:34 UTC, ecmel commented
@ilopmar Pebble's default loader does not work with graalvm native image. I will try to replace the loader.

2020-11-27 09:31 UTC, ecmel commented
@ilopmar Added Pebble branch to https://github.com/micronaut-graal-tests/micronaut-views-graal

2020-11-27 09:36 UTC, ilopmar commented
> @ilopmar Added Pebble branch to https://github.com/micronaut-graal-tests/micronaut-views-graal

Awesome! I'll take a look at that PR soon. Thanks :)

2020-11-27 12:07 UTC, ilopmar commented
I've tested the GraalVM support and works. Unless @graemerocher or @alvarosanchez have any more comments on this PR I think we can merge it for now and release a new version to be included in Micronaut 2.3.
Then @ecmel if you want to add more features/improvements you can send new PRs.

2020-11-27 12:09 UTC, graemerocher commented
Fine by me

2020-11-27 12:18 UTC, merged

2020-11-27 13:24 UTC, ecmel commented
Thank you for merging this pr