ViewModelProcessor Improvements + Documentation
micronaut-projects/micronaut-views pull request #261
Opened 2021-08-08 19:13 UTC by rferreira

* This includes a breaking change to ViewModelProcessor.java
* Grouped all template engines related documentation into a templates subsection
* Grouped all security related pages into a security subsection
* Added documentation page on enhancing models using a custom processors

Fixes #229
Fixes #247

2021-08-08 19:14 UTC, rferreira commented
Sorry for the large PR here folks but most of it is shuffling the template docs into a templates subsection.

2021-08-09 00:56 UTC, rferreira commented on views-core/src/main/java/io/micronaut/views/ViewsFilter.java
> +                .switchMap(response -> {
I did a medium size refactor of the ViewFilter, putting most exits at the top of the method and simplifying the logic (by removing as much of it as possible)

2021-08-09 00:56 UTC, rferreira commented on views-core/src/main/java/io/micronaut/views/ViewsRenderer.java
> +     * @param viewName view name to be rendered
edits here are minor, just some language cleanup

2021-08-09 00:57 UTC, rferreira commented on views-core/src/main/java/io/micronaut/views/ViewsRenderer.java
> +    Map<String, Object> modelOf(@Nullable Object data) {
I contemplated removing this method but I decided for keeping it to minimize the backwards breaking changes

2021-08-09 00:57 UTC, rferreira commented on views-core/src/main/java/io/micronaut/views/model/ViewModelProcessor.java
> +public interface ViewModelProcessor<T> {
Here lies the biggest change, ViewModelProcessors now are typed

2021-08-09 00:57 UTC, rferreira commented on views-core/src/main/java/io/micronaut/views/model/security/SecurityViewModelProcessor.java
> +public class SecurityViewModelProcessor implements ViewModelProcessor<Map<String, Object>> {
Updating existing processors to the new type is as simple as setting the type of Map<String, Object>

2021-08-09 06:57 UTC, sdelamo requested changes

2021-08-09 09:19 UTC, sdelamo commented
Thanks for the contribution @rferreira I have moved the contents of this PR to several PRs:

-  https://github.com/micronaut-projects/micronaut-views/pull/263
- https://github.com/micronaut-projects/micronaut-views/pull/262

2021-08-09 12:14 UTC, sdelamo commented
@rferreira With the above linked PRs and #265 I think it covers everything suggested by this PR. I am going to close this PR.

Please, leave any comments at #265 at let me know if you have any concerns or you think I did not move any necessary changes.

2021-08-09 12:14 UTC, closed without merging