support binary static content in JTE
micronaut-projects/micronaut-views pull request #413
Opened 2022-05-22 00:39 UTC by edward3h

Update JTE to latest version.

Support for 'binary static content' in JTE. This pre-converts Strings to UTF-8 bytes to reduce work during rendering.

2022-05-23 20:18 UTC, sdelamo reviewed
@edward3h Thanks for the contribution. 

could you  add more tests? Could you tests it works both for `binaryStaticContent` true and false. 

not important but we prefer not to use wildcard imports if possible. 

Not sure if it make sense for JTE but since `JteWritable` implements `Writable` it could be possible to just use it as a controller method return. Maybe you could document that. See `RockerWritable`.

2022-05-26 18:46 UTC, edward3h commented
I've made the tests run both ways with the binary output turned on and off. Also changed star imports back to single classes.

I'd like to do something similar to the `RockerWritable` example, but I'm not satisfied with the JTE API for it at the moment. I'll come back to that some time.

2022-05-31 10:14 UTC, graemerocher approved these changes

2022-07-18 05:25 UTC, sdelamo requested changes

2022-07-18 05:25 UTC, sdelamo commented on views-jte/src/main/java/io/micronaut/views/jte/JteViewsRenderer.java
> +    @NonNull
annotate with `@Deprecated`

2022-07-18 07:35 UTC, merged

2022-07-18 07:39 UTC, sdelamo commented on views-jte/src/main/java/io/micronaut/views/jte/JteViewsRenderer.java
> +    @NonNull
resolved via https://github.com/micronaut-projects/micronaut-views/pull/428