Changes to allow compilation against the latest 4.0.0 snapshot
micronaut-projects/micronaut-views pull request #460
Opened 2022-11-04 14:50 UTC by timyates

2022-11-04 14:52 UTC, timyates commented on test-suite/src/test/java/views/NonHTMLViewRendererTest.java
> +    @Serdeable
I do not know why I had to use `@Serdeable` in place of `@Introspected`...  Does 4.0.0 of security switch to serde?

2022-11-07 08:55 UTC, sdelamo requested changes
Please use serde instead jackson

2022-11-07 08:55 UTC, sdelamo commented on views-core/build.gradle
> +    testImplementation(mn.micronaut.serde.jackson)
please, use serde instead

2022-11-07 10:04 UTC, sdelamo requested changes

2022-11-07 10:04 UTC, sdelamo commented on test-suite/build.gradle
> +            strictly("4.0.0-SNAPSHOT")
remove remove https://github.com/micronaut-projects/micronaut-core/pull/8298

2022-11-07 11:57 UTC, timyates commented on test-suite/build.gradle
> +            strictly("4.0.0-SNAPSHOT")
Done https://github.com/micronaut-projects/micronaut-views/pull/460/commits/9d496aaf0966d4c5c942082e69d2d00785f2fbde

2022-11-28 06:34 UTC, sdelamo approved these changes

2022-11-28 06:34 UTC, merged