Describe request attribute containing CSP nonce
micronaut-projects/micronaut-views pull request #898
Opened 2024-10-09 15:01 UTC by tfield

This update explains where the generated nonce value can be accessed on the server, so that template systems utilizing CSP can be able to access the value. Provides a trivial example.

2024-10-09 15:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/micronaut-projects/micronaut-views?pullRequest=898) <br/>All committers have signed the CLA.

2024-10-09 15:35 UTC, graemerocher requested changes

2024-10-09 15:35 UTC, graemerocher commented on src/main/docs/guide/views/security/csp.adoc
> +```html
can you change this to:

```
[source,html]
----
<script type="text/javascript" src="/path/to/script.js" nonce="${cspNonce}" />
----
```

2024-10-14 13:09 UTC, tfield commented on src/main/docs/guide/views/security/csp.adoc
> +```html
Update applied!

2024-10-14 15:44 UTC, graemerocher approved these changes

2024-10-30 14:09 UTC, merged